name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: "Set manifest version number"
        run: |
          python3 ${{ github.workspace }}/.github/scripts/update_hacs_manifest.py --version ${{ steps.release.outputs.tag }}
      - name: Create zip
        run: |
          cd custom_components/ha_heliotherm
          zip ha_heliotherm.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/ha_heliotherm/ha_heliotherm.zip
          asset_name: ha_heliotherm.zip
          tag: ${{ github.ref }}
          overwrite: true
